version: '3'
services:

  consul:
    image: consul:latest
    hostname: consul
    ports:
      - 8300:8300
      - 8500:8500
      - 8600:8600
    command: consul agent -dev -ui -client 0.0.0.0


  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    expose:
      - 9092
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: -Xmx512M -Xms512M


  redis_db:
    image: redis:4.0.10
    ports:
      - 6379:6379


  ms-gw:
    image: alakbarov02/ms-gw
    container_name: ms-gw
    hostname: ms-gw
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    ports:
      - 8081:8081
    depends_on:
      - consul

  ms-order:
    image: alakbarov02/ms-order
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - KAFKA_URI=kafka:9092
      - REDIS_URI=redis_db:6379
    ports:
      - 8082:8082
    depends_on:
      - kafka
      - consul
      - ms-gw


  ms-account:
    image: alakbarov02/ms-account
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - KAFKA_URI=kafka:9092
      - REDIS_URI=redis_db:6379
    ports:
      - 8086:8086
    depends_on:
      - consul
      - kafka
      - ms-gw


  ms-user:
    image: alakbarov02/ms-user
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - KAFKA_URI=kafka:9092
    ports:
      - 8083:8083
    depends_on:
      - kafka
      - consul
      - ms-gw


  ms-stock:
    image: alakbarov02/ms-stock
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - KAFKA_URI=kafka:9092
      - REDIS_URI=redis_db:6379
    ports:
      - 8084:8084
    depends_on:
      - kafka
      - redis_db
      - consul
      - ms-gw


  ms-notification:
    image: alakbarov02/ms-notification
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - KAFKA_URI=kafka:9092
      - EMAIL=matson_02@bk.ru
      - EMAIL_PASSWORD=azh3r!yRcuNdshD
    ports:
      - 8085:8085
    depends_on:
      - kafka
      - consul
      - ms-gw