server:
  port: 0

spring:
  application:
    name: ms-stock
  cloud:
    consul:
      discovery:
        healthCheckPath: /management/health
        instanceId: ${spring.application.name}:${spring.application.instance-id:${random.value}}
      config:
        watch:
          enabled: false

    stream:
      kafka:
        binder:
          brokers: ${KAFKA_URI:localhost:9092}
      bindings:
        orderCreateStateInput:
          destination: create_order
          contentType: application/json
        stockOrderCompleteStateOutput:
          destination: complete_stock_order
          contentType: application/json

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: [ "configprops", "env", "health", "info", "threaddump", "logfile", "prometheus" ]

redis:
  server:
    url: redis://${REDIS_URI:localhost:6379}

order:
  message: "Sizin sifarisiniz {0} eded {1} {2} AZN odenilmekle ugurla {3} tamamlanmisdir"